language:
  - python

os:
  - linux

python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - sudo apt-get update
  # Miniconda is installed so that conda can be used as the package manager rather than pip
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a
  - conda create -q -n install-env python=$TRAVIS_PYTHON_VERSION
  - source activate install-env
  # Taken from https://stackoverflow.com/questions/35802939/install-only-available-packages-using-conda-install-yes-file-requirements-t
  # - while read requirement; do conda install -q -y $requirement || pip install $requirement; done < requirements.txt
  - conda install -q -y --file=requirements.txt
  - conda install -q -y --file=tests/requirements.txt
  - conda install -q -y --file=docs/requirements.txt
  - conda list
  - python setup.py install

script:
  # Tests
  - pytest --cov=pyproprop
  # Docs
  - cd docs; make clean; cd ..
  - sphinx-build -nWT -b dummy docs/source docs/build

notifications:
  slack: 
    rooms: 
      - lapysim:iK2uynW8fR6IbFVTpQwTlbwR#dev
      - lapysim:iK2uynW8fR6IbFVTpQwTlbwR#pyproprop

after_success:
  - codecov