name: test

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout Pyproprop
        uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          activate-environment: test-environment
          python-version: "3.9"
          channels: conda-forge
          conda-build-version: 3.21.4
      - name: Install basic dependencies
        run: conda install -q -y --file=requirements.txt --file=tests/requirements.txt
      - name: Install Pyproprop
        run: python setup.py install
      - name: Test with pytest
        run: pytest tests/
